Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/nix/store/s0p1kr5mvs0j42dq5r08kgqbi0k028f2-python3-3.11.10/lib/python3.11/http/server.py", line 1313, in <module>
    test(
  File "/nix/store/s0p1kr5mvs0j42dq5r08kgqbi0k028f2-python3-3.11.10/lib/python3.11/http/server.py", line 1260, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/s0p1kr5mvs0j42dq5r08kgqbi0k028f2-python3-3.11.10/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/nix/store/s0p1kr5mvs0j42dq5r08kgqbi0k028f2-python3-3.11.10/lib/python3.11/http/server.py", line 1307, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/s0p1kr5mvs0j42dq5r08kgqbi0k028f2-python3-3.11.10/lib/python3.11/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/nix/store/s0p1kr5mvs0j42dq5r08kgqbi0k028f2-python3-3.11.10/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
